name: Build FortniteFix.exe
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install customtkinter pyinstaller
    - run: pyinstaller --onefile --noconsole --name "FortniteFix_v6" FortniteFixApp.py
    - uses: actions/upload-artifact@v4
      with:
        name: FortniteFix_v6_exe
        path: dist/FortniteFix_v6.exe
